"use client";
import MainLayout from "@/components/MainLayout";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ProfileBuilderProvider } from "./Context/ContextProvider";
import { AuthData, AuthProvider } from "./Context/AuthProvider";
import { usePathname } from "next/navigation";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/* export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; */

export default function RootLayout({ children }) {
  const pathname = usePathname();
  const noSidebarRoutes = ["/register", "/Login"];
  const showSidebar = !noSidebarRoutes.includes(pathname);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black`}
      >
        <AuthProvider>
          <ProfileBuilderProvider>
            {showSidebar ? (
              <MainLayout>{children}</MainLayout>
            ) : (
              <div>{children}</div>
            )}
          </ProfileBuilderProvider>
        </AuthProvider>
        <Toaster
          position="top-right" // Set the position to top-right
          reverseOrder={false} // Show the newest toast at the bottom of the stack
          toastOptions={{
            // Optional: Customize default styles
            success: {
              style: {
                background: "#4caf50",
                color: "#fff",
                animation: "slideInLeft 0.5s ease",
              },
            },
            error: {
              style: {
                background: "#f44336",
                color: "#fff",
                animation: "slideInLeft 0.5s ease",
              },
            },
          }}
        />
      </body>
    </html>
  );
}
